### ISSUE TITLE
Certificates Done Right™ (certificate generation)

### ISSUE THREAD

**Issue by RandomReaper** [cloudio-project/cloudio-services#11]
1. Key generation on the client side
2. CSR on the client
3. The client sends the CSR 
4. Certificate signing by the CA (our team).
5. Certificate is installed on the client

Seems really simple (1-2 day coding) using [BountyCastle](https://www.bouncycastle.org/), the critical part is sending the CSR securely and without too much hassle (think of mass-deployment).

**Comment by cm0x4D** [comment]
Certificates are completely backend generated, which IMHO is ok for this purpose.
