### ISSUE TITLE
Add boolean to endpoint parameters to activate/deactivate the endpoint

### ISSUE THREAD

**Issue by cm0x4D** [cloudio-project/cloudio-services#16]
Good idea, will implement it later, will affect all the access control, could open an issues for it

_Originally posted by @lucblender in https://github.com/cloudio-project/cloudio-services/pull/15_

**Comment by lucblender** [comment]
Was the already existing _blocked_ attribute in endpoint entity planned to this purpose?

**Comment by cm0x4D** [comment]
Exactly
