### ISSUE TITLE
ExecJobService

### ISSUE THREAD

**Issue by cm0x4D** [cloudio-project/cloudio-services#31]
https://github.com/cloudio-project/cloudio-services/blob/e3093b7dcbf488eead88baba02741769bd610f31/src/main/kotlin/ch/hevs/cloudio/cloud/services/ExecJobsService.kt#L22-L43

@lucblender What is exactly the point of this service? It does not much yet...

**Comment by lucblender** [comment]
True, I did add it while doing the implementation of the Remote Jobs. Will check tomorrow on the virtual machin if I don't have it modified in some forgotten git commit.

**Comment by lucblender** [comment]
@cm0x4D I checked on my side, I haven't worked on it at all. I let you the pleasure to delete it since you're working on an open pull request.

**Comment by cm0x4D** [comment]
Done, thanks @lucblender.
