### ISSUE TITLE
Endpoint Management -> Update endpoint's configuration parameter.

### ISSUE THREAD

**Issue by MartinMeyer1** [cloudio-project/cloudio-services#89]
The server always respond with a 415 error

**Comment by cm0x4D** [comment]
What's the value of the Content-Type header?

**Comment by cm0x4D** [comment]
Maybe it would be handy to be able to post multiple properties that will then be merged with the existing ones  instead of having to push them one by one. @MartinMeyer1 what do you  mean?

**Comment by MartinMeyer1** [comment]
Thanks for the PR, I initially opened this ticket only as reminder :wink:. 
Yes sure it would be very handy. Btw, this is already possible, but only when generating a token.
As the bug is now fixed, I change the issue label.

**Comment by cm0x4D** [comment]
It was simple to fix and I had some time. I will add the feature for multiple parameters.

**Comment by cm0x4D** [comment]
Fixed in 52ad6009c23d09fccbc10b65b839c0f8290be554
